# VillagerNames configuration file

# Show debug messages
debug: false

# Enable to show villager names without hovering over them
set_custom_name_visible: true

# Whether to include the villager's profession in the name
display_names_with_profession: false

# Potential chance that a villager will have a custom name (values 0 - 1)
spawn_with_name_chance: 1.0

# Full display name for a villager without a profession
full_display_name: "%name%"

# Full display name for a villager with a profession
full_display_name_with_profession: "%name% the %profession%"

# List of villager names
villager_names:
  - "Merek"
  - "Carac"
  - "Ulric"
  - "Tybalt"
  - "Borin"
  - "Sadon"
  - "Terrowin"
  - "Rowan"
  - "Forthwind"
  - "Althalos"
  - "Fendrel"
  - "Brom"
  - "Hadrian"
  - "Lord"
  - "Walter"
  - "Earl"
  - "Sir"
  - "Oliver"
  - "Justice"
  - "Roger"
  - "Joseph"
  - "Geoffrey"
  - "William"
  - "Francis"
  - "Simon"
  - "John"
  - "Edmund"
  - "Charles"
  - "Benedict"
  - "Gregory"
  - "Peter"
  - "Henry"
  - "Frederick"
  - "Thomas"
  - "Arthur"
  - "Bryce"
  - "Donald"
  - "Leofrick"
  - "Letholdus"
  - "Lief"
  - "Barda"
  - "Rulf"
  - "Robin"
  - "Gavin"
  - "Terryn"
  - "Ronald"
  - "Jarin"
  - "Cassius"
  - "Leo"
  - "Cedric"
  - "Peyton"
  - "Josef"
  - "Janshai"
  - "Doran"
  - "Asher"
  - "Quinn"
  - "Zane"
  - "Xalvador"
  - "Favian"
  - "Destrian"
  - "Dain"
  - "Berinon"
  - "Tristan"
  - "Gorvenal"
  - "Millicent"
  - "Alys"
  - "Ayleth"
  - "Anastas"
  - "Alianor"
  - "Cedany"
  - "Ellyn"
  - "Helewys"
  - "Malkyn"
  - "Peronell"
  - "Sybbyl"
  - "Ysmay"
  - "Thea"
  - "Jacquelyn"
  - "Amelia"
  - "Gloriana"
  - "Good"
  - "Catherine"
  - "Anne"
  - "Mary"
  - "Arabella"
  - "Elizabeth"
  - "Hildegard"
  - "Brunhild"
  - "Adelaide"
  - "Alice"
  - "Beatrix"
  - "Cristiana"
  - "Eleanor"
  - "Emeline"
  - "Isabel"
  - "Juliana"
  - "Margaret"
  - "Matilda"
  - "Mirabelle"
  - "Rose"
  - "Helena"
  - "Guinevere"
  - "Isolde"
  - "Maerwynn"
  - "Muriel"
  - "Winifred"
  - "Godiva"
  - "Catrain"
  - "Angmar"
  - "Gussalen"
  - "Jasmine"
  - "Josselyn"
  - "Maria"
  - "Victoria"
  - "Gwendolynn"
  - "Enndolynn"
  - "Janet"
  - "Luanda"
  - "Krea"
  - "Rainydayas"
  - "Atheena"
  - "Dimia"
  - "Phrowenia"
  - "Aleida"
  - "Ariana"
  - "Alexia"
  - "Katelyn"
  - "Katrina"
  - "Loreena"
  - "Kaylein"
  - "Seraphina"
  - "Duraina"
  - "Ryia"
  - "Farfelee"
  - "Iseult"
  - "Brangian"
  - "Elspeth"
  - "James"
  - "Daniel"
