main: com.adenark.villagernames.VillagerNames
name: VillagerNames
version: 1.0-SNAPSHOT
api-version: 1.19
description: This plugin assigns Minecraft villagers a randomized name.
authors: [adenark, Mancdev]
commands:
  villagernames:
    description: VillagerNames plugin help
    usage: /<command>
    permission: villagernames.help
