name: VillagerNames
version: 1.3
author: Mancdev
main: com.adenark.villagernames.VillagerNames
website: https://mancdev.com
commands:
  va:
    description: VillagerNames plugin help
    usage: /<command>
    permission: villagernames.help
    aliases: [va, villagernames]